### ISSUE TITLE
Add support ttypescript transformer interface 

### ISSUE THREAD

**Issue by cevek** [kimamula/ts-transformer-keys#12]
I wrote a tool which patch ts on the fly and add support for custom transformers from `tsconfig.json`
https://github.com/cevek/ttypescript
```
{
    "compilerOptions": {
        "plugins": [
            {
                "customTransformers": {
                    "before": ["ts-transformer-keys"],
                }
            }
        ]
    }
}
```

but it works slightly different by calling your transformer directly and provide the `program` as second argument
This is transformer example:
```ts
import * as ts from 'typescript';
export default (ctx: ts.TransformationContext, program: ts.Program): ts.Transformer<ts.SourceFile> => {
    return sourceFile => {
        function visitor(node: ts.Node): ts.Node {
            return ts.visitEachChild(node, visitor, ctx);
        }
        return ts.visitEachChild(sourceFile, visitor, ctx);
    };
};
```
If you accept PR, I can add support for this

**Comment by kimamula** [comment]
I really love your tool.
However, I feel a little hesitant to expose an additional interface especially for your tool as one can easily wrap my transformer as follows to use it with your tool.

```js
const keysTransformer = require('ts-transformer-keys/transformer').default;
export default (ctx, program) => keysTransformer(program)(ctx);
```

What do you think?

I hope tsconfig could be written in JS or TS [as suggested](https://github.com/Microsoft/TypeScript/issues/20110#issuecomment-345384878).

**Comment by cevek** [comment]
I think about a setting type of transformer, something like that 
`{module: 'ts-transformer-keys', type: 'program'}` that will do it automatically, 
 because your transformer pattern is common

**Comment by kimamula** [comment]
Looks like you recently added `PluginConfig.type` config to support variety of types of transformer functions.

Is it possible to add another `PluginConfig.type` to support `(program: ts.Program) => (ctx: ts.TransformationContext) => TransformerPlugin` type of transformer?

**Comment by cevek** [comment]
So, your pattern already supports - it is `program` type and it is by default
```
(program: ts.Program, config?: PluginConfig) => ts.TransformerFactory<ts.SourceFile>
type TransformerFactory = (context: TransformationContext) => Transformer<T>;
```
so you can just use it like 

```
compilerOptions: {
 plugins: [
   { "transform": "transformer-module",  someConfig: true }
 ]
}
```

**Comment by kimamula** [comment]
Ah, I see. That's great, thanks!

Then I close this issue.
