### ISSUE TITLE
Document option of using ttypescript

### ISSUE THREAD

**Issue by strongpauly** [kimamula/ts-transformer-keys#14]
Seems pretty easy to set this transformer up using ttypescript (https://github.com/cevek/ttypescript).  This should be presented as an option in the documentation.  Simply setup ttypescript and add this to your tsconfig.json compiler options:

`"plugins": [
            { "transform": "ts-transformer-keys/transformer"}
 ]`

**Comment by kimamula** [comment]
Thanks for the suggestion!
I have added example usages with webpack, Rollup, and ttypescript.
