### ISSUE TITLE
Any option to handle union types ?

### ISSUE THREAD

**Issue by NN---** [kimamula/ts-transformer-keys#15]
Question.
Supposing I have a string literal union type, is there a way to generate its strings ?

```ts
type X = "A" | "B" | "C";

// generate: ["A", "B", "C"]
```

**Comment by kimamula** [comment]
Use [ts-transformer-enumerate](https://github.com/kimamula/ts-transformer-enumerate).

```ts
import { enumerate } from 'ts-transformer-enumerate';

type X = "A" | "B" | "C";
const Xs = Object.keys(enumerate<X>()); // ["A", "B", "C"]
```

**Comment by redbaron** [comment]
@kimamula, type of Xs is string[] due to Object.keys() not inverring result type. Is there a way to get type of X[] instead?

**Comment by kimamula** [comment]
@redbaron If your TypeScript configuration allows you to use `Object.values()`, use it instead of `Object.keys()` and that should work.

**Comment by redbaron** [comment]
Doesn't Object.values() return .. values?  :)

**Comment by IanBellomy** [comment]
> @redbaron If your TypeScript configuration allows you to use `Object.values()`, use it instead of `Object.keys()` and that should work.

I get ‘unknown[]‘ that way...

**Comment by kimamula** [comment]
I'm sorry that I made a wrong answer.
With recent versions of TypeScript, you can achieve this with [`const` assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions).

```ts
const Xs = ['x', 'y', 'z'] as const
type X = typeof Xs[number] // 'x' | 'y' |'z'
```

Therefore, you don't need `ts-transformer-enumerate` any more.
