### ISSUE TITLE
Non-existent export 'keys' is imported from 'ts-transformer-keys'

### ISSUE THREAD

**Issue by Darmody** [kimamula/ts-transformer-keys#23]
<img width="639" alt="屏幕快照 2019-08-05 22 37 17" src="https://user-images.githubusercontent.com/6788752/62472605-b38e3500-b7d1-11e9-97bd-1fd979b69c92.png">

it works but get a warning, how to avoid it?

**Comment by kimamula** [comment]
I am not familiar with Rollup but it is likely you can use `onwarn` to avoid this warning.

```js
// rollup.config.js
export default {
  // ...
  onwarn(warning, warn) {
    if (warning.code === 'NON_EXISTENT_EXPORT' && warning.name === 'keys') {
      return;
    }
    warn(warning);
  }
}
```

However, this inhibits any warning for `NON_EXISTENT_EXPORT` with the name of `keys`.
Hope someone knows the better solution.
