### ISSUE TITLE
Why does keys() not work with dynamic inputs?

### ISSUE THREAD

**Issue by niksrid** [kimamula/ts-transformer-keys#38]
Hello,

I was just wondering why does the keys function not work with dynamic names passed to it?

Is this because of an inherent TypeScript limitation or is it a transformation function limitation?

For reference, this is what my code roughly looks like right now but does not seem to work
`const instances = ['a','b','c'];`
 `for(let instance of instances){`
  `let instanceKeys = keys<NexusPrismaTypes[instance]>();`
  `console.log(instanceKeys) //Returns an empty array`
  `}`

**Comment by kimamula** [comment]
I think you just missed `typeof`. This should work:

```ts
const instances = ['a','b','c'];
for(let instance of instances){
  // add typeof in front of instance
  let instanceKeys = keys<NexusPrismaTypes[typeof instance]>();
  console.log(instanceKeys);
}
```

**Comment by kimamula** [comment]
Probably you also need `as const`.

```ts
// add 'as const'
const instances = ['a','b','c'] as const;
for(let instance of instances){
  // add typeof in front of instance
  let instanceKeys = keys<NexusPrismaTypes[typeof instance]>();
  console.log(instanceKeys);
}
```
