### ISSUE TITLE
Calling instance method from getter in VueSingleFileComponent causes error: Cannot find module

### ISSUE THREAD

**Issue by Buntelrus** [kimamula/ts-transformer-keys#47]
I've a vue 3 project with typescript and I'm trying to get ts-transformer-keys work.

My configuration:

tsconfig.json:
```json
"plugins": [
      { "transform": "ts-transformer-keys/transformer" }
]
```

vue.config.js
```js
chainWebpack: config => {
    ['ts', 'tsx'].forEach(rule => {
      config.module
        .rule(rule)
        .use('ts-loader')
        .tap(options => Object.assign(options, {
          compiler: 'ttypescript',
          transpileOnly: false
        }))
    })
  }
```

I could locate the issue in the following problem:
If I call an instance method from a getter I got an error 
> Error: Cannot find module 'C:\path\src\App.vue.ts'

Without `ts-transformer-keys` this works fine.

For Example:
App.vue:

```vue
<template>
  <p>{{ message }}</p>
  <p>{{ messageAlias }}</p>
  <p>{{ upperCaseMessage }}</p>
  <p>{{ messageToUpperCase }}</p>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'
export default class App extends Vue {
  message = 'hello World'

  get messageAlias() {
    return this.message
  }

  get upperCaseMessage() {
    // return this.message.toUpperCase() // this will work
    return this.messageToUpperCase() // this won't
  }

  messageToUpperCase() {
    return this.message.toUpperCase()
  }
}
</script>
```

**Comment by kimamula** [comment]
Could you provide a repository that can reproduce the problem?
I have tried to reproduced your problem but encountered a different error.

```sh
ERROR in src/App.vue:9:10
TS2614: Module '"../node_modules/vue-class-component/lib"' has no exported member 'Vue'. Did you mean to use 'import Vue from "../node_modules/vue-class-component/lib"' instead?
     7 | 
     8 | <script lang="ts">
  >  9 | import { Vue } from 'vue-class-component'
       |          ^^^
    10 | export default class App extends Vue {
    11 |   message = 'hello World'
    12 | 
```

**Comment by Buntelrus** [comment]
https://github.com/Buntelrus/ts-transformer-keys_issues_47 here you go.

The relevant code is in [src/App.vue](https://github.com/Buntelrus/ts-transformer-keys_issues_47/blob/main/src/App.vue)

**Comment by kimamula** [comment]
@Buntelrus Thanks for reporting. Fixed in v0.4.3.

**Comment by Buntelrus** [comment]
thanks you

**Comment by Buntelrus** [comment]
If I try to build my project I got now following error in the browser console:
![image](https://user-images.githubusercontent.com/26169329/101027312-28b17c00-3578-11eb-912b-e7fada3e3680.png)

while `vue-cli-service serve` has no issue. You can reproduce the problem with the mentioned repo.

**Comment by kimamula** [comment]
When I tried `yarn build --mode development`, it worked fine. I guess some build setting that is specific to production is preventing the transformer from working properly.

[A similar problem](https://github.com/kimamula/ts-transformer-keys/issues/4#issuecomment-672426965) was found before. But this time `onlyCompileBundledFiles` does not seem to be the cause of the problem.
