### ISSUE TITLE
How to use with this with React + Typescript?

### ISSUE THREAD

**Issue by LyhourChhen** [kimamula/ts-transformer-keys#52]
I pretty new to the typescript world, but figure out if I could extract the key from the interface it would be a perfect fit for what I need in react, but I can't find any tutorial to add it with React.

**Comment by kimamula** [comment]
It depends on which tool you are using to compile TypeScript.
There are several examples [here](https://github.com/kimamula/ts-transformer-keys/tree/master/examples).

Unfortunately, if you use Babel to compile TypeScript, it is not possible to use ts-transformer-keys (#32)

**Comment by LyhourChhen** [comment]
Thank you sir
