### ISSUE TITLE
Support for gulp

### ISSUE THREAD

**Issue by unnieayilliath** [kimamula/ts-transformer-keys#57]
Hi,
Does this work with gulp? Is there any documentation on that?

**Comment by kimamula** [comment]
You can make this work by using webpack, Rollup, or ttypescript in a gulp task. Please refer to the corresponding documentations to see how to use these tools in a gulp task.

- webpack: https://www.npmjs.com/package/webpack-stream
- Rollup: https://www.npmjs.com/package/@rollup/stream
- ttypescript: https://github.com/cevek/ttypescript/issues/98

After deciding which tool to use, please refer to the README of this repo to see how to configure the selected tool to use the transformer.
