### ISSUE TITLE
Get required Properites

### ISSUE THREAD

**Issue by adeelhussain** [kimamula/ts-transformer-keys#61]
Is there any way of getting required properties only?

**Comment by kimamula** [comment]
I think you can do something like this.

```ts
import { keys } from 'ts-transformer-keys';

interface Props {
    a?: number;
    b: string;
}

type RequiredOnly<T> = {
    [P in keyof T]: NonNullable<T[P]>;
};

const requiredProps = keys<RequiredOnly<Props>>(); // ['b']
```

**Comment by Keith-Hon** [comment]
possible to add this function to the library?

sth like 

import { requiredKeys } from 'ts-transformer-keys';

**Comment by Keith-Hon** [comment]
> 

Hi, do you demo codes for this? I can only get all fields instead of just requirede fields.
