### ISSUE TITLE
How to get required and optional properties

### ISSUE THREAD

**Issue by Keith-Hon** [kimamula/ts-transformer-keys#80]
related to https://github.com/kimamula/ts-transformer-keys/issues/61

https://codesandbox.io/s/github/Keith-Hon/ttsc-codesandbox-demo/tree/master/

https://github.com/Keith-Hon/ttsc-codesandbox-demo

**Comment by kimamula** [comment]
Could you explain in more detail? Your CodeSandbox example is showing required and optional properties.

```
{"requiredProps":["b"],"optionalProps":["a"]}
```

**Comment by Keith-Hon** [comment]
Hi, I originally wanted to ask how to required and optional properties, but I figured that out myself. It would be great to have such functions defined in your library as well.

**Comment by kimamula** [comment]
Hmm, I want to follow the Unix philosophy "Do One Thing And Do It Well" here. I love the fact that this package can be used in a variety of ways in combination with various TypeScript techniques by just providing a very simple function.
