### ISSUE TITLE
windows, index.ts path slash unmatch

### ISSUE THREAD

**Issue by karikera** [kimamula/ts-transformer-keys#9]
const indexTs = declaration.getSourceFile().fileName
// indexTs == D:/path/to/node_modules/ts-transformer-keys/index.ts

const indexTs = path.join(__dirname, 'index.ts');
// indexTs == D:\path\to\node_modules\ts-transformer-keys\index.ts

**Comment by kimamula** [comment]
Thanks for reporting!
I have fixed the issue and published v0.3.1.
